import requests
import time

# The address of your running API Bridge
API_URL = "http://localhost:5000"

# Fake clothing suggestions generated by the AI
ai_suggestions = ["red dress", "jackets", "shoes", "blue shirt"]

print("🤖 Starting Mock AI Agents Test...\n")

# 1. Simulate a customer walking through the door
print("--- Triggering Door Sensor ---")
try:
    response = requests.post(f"{API_URL}/sensor/door")
    print(f"API Response: {response.json()}\n")
except requests.exceptions.ConnectionError:
    print("Error: Make sure your api_bridge.py is running in another terminal!\n")
    exit()

time.sleep(2) # Wait 2 seconds

# 2. Simulate the AI agents sending coordinates to the robot
print("--- Triggering Multi-Agent Clothing Suggestions ---")
for item in ai_suggestions:
    print(f"AI Agent wants to send the robot to: '{item}'")
    payload = {"target": item}
    
    response = requests.post(f"{API_URL}/robot/navigate", json=payload)
    
    # Notice what happens when it tries to find the "blue shirt" which isn't in your coordinate map!
    if response.status_code == 200:
        print(f"✅ Success: {response.json()}\n")
    else:
        print(f"❌ Failed: {response.json()}\n")
        
    time.sleep(2) # Wait 2 seconds before the next command