"""
RLRoundStore — on-policy transition cache + rollout batching for PPO.
─────────────────────────────────────────────────────────────────────
Mirrors the `history` singleton pattern in multi_agent/history.py.

PPO is **on-policy**: an update must use data generated by the policy version
being updated.  We therefore collect the transitions of several rounds while the
policy is frozen, then hand the whole batch to the policy for one PPO update and
discard it.  This store is that rollout buffer plus the bookkeeping needed to:

  - recover a round's transitions when a (delayed) emoji rating arrives, and
  - assemble the on-policy batch once enough rounds have been settled.

A "transition" is one item the RL agent scored in a round: its features, the
sampled action (score-logit), the log-prob and value at action time, and the
reward accumulated for it.  Rewards arrive from two sources (both preserved from
the original design):

  - passrate_reward(passed, chosen)  → round-level pass-rate, anchored at 10%
  - rating_reward(rating)            → per-item 1–5 emoji satisfaction (3 = 0)
"""

from __future__ import annotations

import logging
import threading
from collections import OrderedDict
from dataclasses import dataclass, field
from typing import Optional

from multi_agent.config import (
    PASSRATE_ANCHOR,
    PPO_ROLLOUT_ROUNDS,
    RL_REWARD_MODE,
    RL_ROUND_CACHE,
    TOP_K,
    ZERO_PASS_PENALTY,
)

logger = logging.getLogger(__name__)


# ── Transition ──────────────────────────────────────────────────────────────────

@dataclass
class Transition:
    """One (item, action) sample the RL agent produced in a round."""
    item_key: str
    x:        list[float]   # feature vector
    action:   float         # sampled score-logit z
    logprob:  float         # log π_old(z | x)
    value:    float         # V_old(x), the critic baseline at action time
    score:    float         # sigmoid(z) — the score actually proposed to Borda
    reward:   float = 0.0   # accumulated return (pass-rate + emoji), filled in later


@dataclass
class _RoundData:
    transitions: dict[str, Transition] = field(default_factory=dict)
    settled:     bool = False


# ── Reward functions ────────────────────────────────────────────────────────────

def passrate_reward(passed: int, chosen: int) -> float:
    """
    Round-level reward for how many of the agent's `chosen` top picks reached the
    final top-10.  Anchored so PASSRATE_ANCHOR (10%) yields 0:

        passed == 0       → ZERO_PASS_PENALTY (-1.5)
        p >= anchor       → (p - anchor) / (1 - anchor)   →   0 .. +1
        0 <  p <  anchor  → (p - anchor) / anchor         →  -1 ..  0
    """
    if chosen <= 0:
        return 0.0
    if passed <= 0:
        return ZERO_PASS_PENALTY
    p = passed / chosen
    if p >= PASSRATE_ANCHOR:
        return (p - PASSRATE_ANCHOR) / (1.0 - PASSRATE_ANCHOR)
    return (p - PASSRATE_ANCHOR) / PASSRATE_ANCHOR


def rating_reward(rating: int) -> float:
    """
    Map a 1–5 emoji rating (3 = neutral) to a reward in [-1, +1]:
        (rating - 3) / 2  →  1→-1.0, 2→-0.5, 3→0.0, 4→+0.5, 5→+1.0
    """
    r = max(1, min(5, int(rating)))
    return (r - 3) / 2.0


# ── Store / rollout buffer ────────────────────────────────────────────────────

class RLRoundStore:
    """Thread-safe transition cache + on-policy rollout batching for PPO."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._rounds: "OrderedDict[str, _RoundData]" = OrderedDict()
        self._settled_order: list[str] = []   # settled rounds awaiting the next PPO update
        # When True, settle_round never auto-consumes a full rollout — the caller
        # drives PPO updates explicitly via drain_rollout(). The experiment curve
        # harness sets this so each episode's emoji reward can land BEFORE its
        # round is consumed. Off in production (settle_round consumes normally).
        self.defer_consumption = False

    # ── Writers ───────────────────────────────────────────────────────────────

    def record_transitions(self, conv_id: str, transitions: dict[str, Transition]) -> None:
        """Cache the RL agent's transitions for a round (called at scoring time)."""
        if not conv_id or not transitions:
            return
        with self._lock:
            self._rounds[conv_id] = _RoundData(transitions=transitions)
            self._rounds.move_to_end(conv_id)
            while len(self._rounds) > RL_ROUND_CACHE:
                old_id, _ = self._rounds.popitem(last=False)
                if old_id in self._settled_order:
                    self._settled_order.remove(old_id)

    def add_reward(self, conv_id: str, item_key: str, reward: float) -> bool:
        """
        Add reward to one item's transition (emoji feedback).  Works until the
        round is consumed by a PPO update.  Returns True if the transition was
        found and updated.
        """
        with self._lock:
            rd = self._rounds.get(conv_id)
            if rd and item_key in rd.transitions:
                rd.transitions[item_key].reward += reward
                return True
        return False

    def settle_round(self, conv_id: str, final_keys: set[str]) -> Optional[list[Transition]]:
        """
        Apply the pass-rate reward for a finished round and mark it settled.

        The agent's "chosen" set = its top-TOP_K items by proposed score; each
        gets the round-level pass-rate reward added to its transition.  Once
        PPO_ROLLOUT_ROUNDS rounds have been settled, returns the full on-policy
        batch (and clears it from the store); otherwise returns None.
        """
        with self._lock:
            rd = self._rounds.get(conv_id)
            if rd is None or rd.settled:
                return None

            ranked = sorted(rd.transitions.values(), key=lambda t: -t.score)
            chosen = ranked[:TOP_K]
            passed = sum(1 for t in chosen if t.item_key in final_keys)
            # RL_REWARD_MODE="rating" zeroes the pass-rate contribution so the
            # learning signal is purely the emoji/review reward; "passrate"/"both"
            # keep the pass-rate reward (production default = "both").
            reward = 0.0 if RL_REWARD_MODE == "rating" else passrate_reward(passed, len(chosen))
            for t in chosen:
                t.reward += reward

            rd.settled = True
            self._settled_order.append(conv_id)
            logger.info(
                f"[{conv_id}] RL pass-rate: {passed}/{len(chosen)} advanced "
                f"→ reward={reward:+.3f}  (settled {len(self._settled_order)}/{PPO_ROLLOUT_ROUNDS})"
            )

            # Deferred mode never auto-consumes (the curve harness drains
            # explicitly); otherwise wait until a full rollout has accumulated.
            if self.defer_consumption or len(self._settled_order) < PPO_ROLLOUT_ROUNDS:
                return None

            # Assemble the on-policy batch and evict the consumed rounds.
            batch: list[Transition] = []
            for cid in self._settled_order:
                rd_done = self._rounds.pop(cid, None)
                if rd_done:
                    batch.extend(rd_done.transitions.values())
            self._settled_order.clear()
            return batch

    def drain_rollout(self) -> Optional[list[Transition]]:
        """Pop the oldest full rollout for an explicit PPO update (deferred mode).

        Returns a batch of the oldest ``PPO_ROLLOUT_ROUNDS`` settled rounds'
        transitions (and evicts them), or ``None`` if fewer than a full rollout
        have settled. Call repeatedly to drain multiple rollouts.
        """
        with self._lock:
            if len(self._settled_order) < PPO_ROLLOUT_ROUNDS:
                return None
            batch: list[Transition] = []
            for _ in range(PPO_ROLLOUT_ROUNDS):
                cid = self._settled_order.pop(0)
                rd_done = self._rounds.pop(cid, None)
                if rd_done:
                    batch.extend(rd_done.transitions.values())
            return batch

    # ── Introspection ───────────────────────────────────────────────────────────

    def pending_rounds(self) -> int:
        with self._lock:
            return len(self._settled_order)


# ── Module-level singleton ──────────────────────────────────────────────────────
rl_store: RLRoundStore = RLRoundStore()
