export const COLORS = {
  short_sleeve_top: '#ff6464',
  long_sleeve_top: '#ffa03c',
  short_sleeve_outwear: '#50c878',
  long_sleeve_outwear: '#28b4c8',
  vest: '#b450ff',
  sling: '#ff50b4',
  shorts: '#64b4ff',
  trousers: '#3c50c8',
  skirt: '#dcb428',
  short_sleeve_dress: '#ff7850',
  long_sleeve_dress: '#8c3cc8',
  vest_dress: '#c86496',
  sling_dress: '#64c8b4',
};

export const EMOJI = {
  short_sleeve_top: '<i class="fas fa-shirt"></i>',
  long_sleeve_top: '<i class="fas fa-shirt"></i>',
  short_sleeve_outwear: '<i class="fas fa-vest"></i>',
  long_sleeve_outwear: '<i class="fas fa-vest"></i>',
  vest: '<i class="fas fa-vest"></i>',
  sling: '<i class="fas fa-dress"></i>',
  shorts: '<i class="fas fa-person-hiking"></i>',
  trousers: '<i class="fas fa-person"></i>',
  skirt: '<i class="fas fa-dress"></i>',
  short_sleeve_dress: '<i class="fas fa-dress"></i>',
  long_sleeve_dress: '<i class="fas fa-dress"></i>',
  vest_dress: '<i class="fas fa-dress"></i>',
  sling_dress: '<i class="fas fa-dress"></i>',
};

export const NAME_TO_HEX = {
  black: '#000000',
  white: '#ffffff',
  gray: '#808080',
  light_gray: '#c8c8c8',
  red: '#dc143c',
  maroon: '#800000',
  pink: '#ff69b4',
  orange: '#ffa500',
  yellow: '#ffd700',
  beige: '#f5f5dc',
  brown: '#964b00',
  olive: '#808000',
  green: '#228b22',
  teal: '#008080',
  cyan: '#00ffff',
  blue: '#1e90ff',
  navy: '#000080',
  purple: '#800080',
  lavender: '#e6e6fa',
  mauve: '#e0b0ff',
  mint: '#98ff98',
  coral: '#ff7f50',
  gold: '#d4af37',
  burgundy: '#800020',
  cream: '#fffdd0',
};

export const AUTO_SCAN_FRAMES_REQUIRED = 8;
export const SILENCE_TIMEOUT_MS = 2500;
export const SPEECH_START_THRESHOLD = 0.03;
export const SPEECH_CONTINUE_THRESHOLD = 0.018;

export const state = {
  ws: null,
  selectedPersona: null,
  userHeightCm: null,
  autoScanFrames: 0,
  autoScanTimeout: null,
  frozen: false,
  currentSessionId: null,
  currentDetectedCategories: [],
  currentRecommendations: [],
  chatHistory: [],
  chatConversationState: null,
  currentActiveFilters: {},
  cameraReady: false,
  pendingStart: false,
  cameraSuspended: false,
  hasShownInitialRecommendationsModal: false,
  recommendationDetailIndex: 0,
  hasChatIntroLoaded: false,
  introRequestInFlight: false,
  introRequestToken: 0,
  agentRoundGeneration: 0,
  currentDetectedBodyType: '',
  currentDetectedClothingType: '',
  currentDetectedColor: '',
  currentView: 'camera',
  mediaRecorder: null,
  audioChunks: [],
  isListening: false,
  micDevicesLoaded: false,
  currentAudioMimeType: '',
};
